[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79

[tool.flake8]
max-line-length = 79
ignore = [
    "W503",
    "F811"
]
exclude = [
    "tests/",
    "*/migrations/",
    "venv/",
    "*/venv/",
    "env/",
    "*/env/"
]