[tool.flake8]
max-line-length = 88
ignore = [
    "W503",
    "F811"
]
exclude = [
    "tests/",
    "*/migrations/",
    "venv/",
    "*/venv/",
    "env/",
    "*/env/"
]


[tool.isort]
profile = "black"
src_paths = ["src"]
known_first_party = ["src"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.ruff]
src = ["src"] # Указывает, что src/ — корень для импортов
line-length = 88
target-version = "py310" # Укажите вашу версию Python (например, 3.10)

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I", "ANN"] # Правила линтинга
ignore = [
    "ANN101", # Игнорировать отсутствие аннотаций для self/cls в методах
    "ANN102",  # Игнорировать отсутствие аннотаций для cls в методах классов
    "ANN401"  # Игнорируйте ANN401 (динамические типы), если используете Any в Pydantic-моделях
]
extend-safe-fixes = ["ANN101", "ANN102"] # Разрешить автоматическое исправление

[tool.ruff.lint.isort]
known-first-party = ["src"] # Указывает, что src — ваш модуль

[tool.ruff.format]
quote-style = "double" # Использовать двойные кавычки, как в Black
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
